/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Exportation.Excel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.mxrck.autocompleter.TextAutoCompleter;
import domain.Client;
import domain.Agent;
import domain.Driver;
import domain.Order;
import domain.OrderPart1;
import domain.Product;
import exceptions.ListException;
import exceptions.StackException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.Queue;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import logic.Data;
import logic.LinkedStack.LinkedStack;
import logic.Logic;

/**
 *
 * @author hvill
 */
public class AdministratorInterface extends javax.swing.JFrame {

    //Instancias
    private Data data;
    private Logic logic;

    private TextAutoCompleter textAutoCompleterClient;
    private TextAutoCompleter textAutoCompleterAgent;
    private TextAutoCompleter textAutoCompleterDriver;

    //Table
    private DefaultTableModel tableModel;
    private int contTable;

    //TDAs
    private LinkedStack orderPart1Stack;
    private LinkedList<Client> clientsList;
    private LinkedList<Agent> agentsList;
    private Queue<Driver> driversList;

    //Filtro tabla
    TableRowSorter trs;

    /**
     * Creates new form NewJFrame
     *
     * @throws exceptions.ListException
     * @throws java.io.IOException
     * @throws exceptions.StackException
     */
    public AdministratorInterface() throws ListException, IOException, StackException {
        initComponents();
        this.setLocationRelativeTo(null);

        //Instancias
        data = new Data();
        logic = new Logic();

        //TDAs
        clientsList = data.getClientsList();
        agentsList = data.getAgentsList();
        driversList = data.getDriversList();
        orderPart1Stack = data.getOrdersPart1Stack();

        //autocompleter
        textAutoCompleterClient = new TextAutoCompleter(jTextFieldEmail);
        textAutoCompleterAgent = new TextAutoCompleter(jTextFieldCorreoAgente);
        textAutoCompleterDriver = new TextAutoCompleter(jTextFieldNameDriver);

        //Tabla
        contTable = 0;
        
        //Inicializa la tabla
        initializeTable();
        //Llena la tabla
        updateTableData();
        //Llena el autocompleter
        fillAutoCompleterClients();
        fillAutoCompleterAgents();
        fillAutoCompleterDrivers();

    }

    /**
     * Metodo para inicializar la tabla con la cantidad de columnas deseadas.
     */
    private void initializeTable() {
        String x[][] = {};
        String columns[] = {"ID Order", "ID Client", "ID Restaurant", "ID Product", "Quantity", "Total Items", 
            "Agent Name", "Date", "Total Order", "Province", "Address", "Driver"};
        tableModel = new DefaultTableModel(x, columns);
        jTableOrders.setModel(tableModel);
    }

    /**
     * Carga datos de tipo Product a la tabla..
     *
     * @param product
     */
    private void updateTableData() throws StackException {
        LinkedStack auxStack = new LinkedStack();
        //Paso todos los elementos de la pila original a una auxiliar para cimplir con el funcionamiento de la pila
        while (!orderPart1Stack.isEmpty()) {
            auxStack.push(orderPart1Stack.pop());
        }
        //Ahora devuelvo los elementos a la pila original añadiendolos a la ves a la tabla
        while (!auxStack.isEmpty()) {
            logic.addOrderPart1InOrdersTable((OrderPart1) auxStack.peek(), tableModel, contTable);
            orderPart1Stack.push(auxStack.pop());
        }
        logic.addOrderPart2InOrdersTable(tableModel, contTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOrders = new javax.swing.JTable();
        jButtonExcell = new javax.swing.JButton();
        jButtonPDF = new javax.swing.JButton();
        jTextFieldClientFiltrer = new javax.swing.JTextField();
        jTextFieldOrderFiltrer = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelNombreCliente = new javax.swing.JLabel();
        jLabelCorreoCliente = new javax.swing.JLabel();
        jLabelTelefonoCliente = new javax.swing.JLabel();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPhoneClient = new javax.swing.JTextField();
        jButtonEliminarCliente = new javax.swing.JButton();
        jButtonEditarCliente = new javax.swing.JButton();
        jLabelProvince = new javax.swing.JLabel();
        jLabelAdress = new javax.swing.JLabel();
        jTextFieldAdressClient = new javax.swing.JTextField();
        jButtonAgregarCliente = new javax.swing.JButton();
        jComboBoxProvinceClient = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIdClient = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldLastNameClient = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldLastName2Client = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCorreoAgente = new javax.swing.JTextField();
        jTextFieldNombreAgente = new javax.swing.JTextField();
        jTextFieldCodigoAgente = new javax.swing.JTextField();
        jTexFieldUsuarioAgente = new javax.swing.JTextField();
        jButtonAgregarAgente = new javax.swing.JButton();
        jButtonEditAgent = new javax.swing.JButton();
        jButtonDeleteAgent = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPasswordFieldAgente = new javax.swing.JPasswordField();
        jButtonCleanAgent = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldIDDriver = new javax.swing.JTextField();
        jTextFieldNameDriver = new javax.swing.JTextField();
        jTextFieldLastName1Driver = new javax.swing.JTextField();
        jTextFieldLastName2Driver = new javax.swing.JTextField();
        jTextFieldPhoneDriver = new javax.swing.JTextField();
        jTextFieldTypeVehicle = new javax.swing.JTextField();
        jTextFieldPlateDriver = new javax.swing.JTextField();
        jTextFieldAgeDriver = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextFieldCedulaDriver = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        IdRestaurant = new javax.swing.JLabel();
        NameRestaurant = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTexFieldIdProduct = new javax.swing.JTextField();
        jTextFieldNameProduct = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldPriceProduct = new javax.swing.JTextField();
        jComboBoxRestaurant = new javax.swing.JComboBox<>();
        jComboBoxType = new javax.swing.JComboBox<>();
        jButtonAddProduct = new javax.swing.JButton();
        jButtonUpdateProduct = new javax.swing.JButton();
        jButtonDeleteProduct = new javax.swing.JButton();
        jButtonDireccionProducto = new javax.swing.JButton();
        jTextFieldAdressProduct = new javax.swing.JTextField();
        jButtonCleanProduct = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelBorder = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelFonoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        jScrollPane1.setViewportView(jTableOrders);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1175, 195));

        jButtonExcell.setText("Exportar Excell");
        jButtonExcell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcellActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcell, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 348, -1, -1));

        jButtonPDF.setText("Exportar PDF");
        jButtonPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPDFActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 348, -1, -1));

        jTextFieldClientFiltrer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldClientFiltrerKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldClientFiltrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 90, -1));

        jTextFieldOrderFiltrer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldOrderFiltrerKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldOrderFiltrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 93, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoAzul.png"))); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        jTabbedPane1.addTab("Control General", jPanel1);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1165, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reportes", jPanel2);

        jLabelNombreCliente.setText("Name:");

        jLabelCorreoCliente.setText("Email:");

        jLabelTelefonoCliente.setText("Phone:");

        jTextFieldNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreClienteActionPerformed(evt);
            }
        });

        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusGained(evt);
            }
        });
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jTextFieldPhoneClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneClientActionPerformed(evt);
            }
        });

        jButtonEliminarCliente.setText("delete client");
        jButtonEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarClienteActionPerformed(evt);
            }
        });

        jButtonEditarCliente.setText("Edit Client");
        jButtonEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarClienteActionPerformed(evt);
            }
        });

        jLabelProvince.setText("Province:");

        jLabelAdress.setText("Adress:");

        jButtonAgregarCliente.setText("add client");
        jButtonAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarClienteActionPerformed(evt);
            }
        });

        jComboBoxProvinceClient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San Jose", "Alajuela", "Heredia", "Cartago", "Guanacaste", "Puntarenas", "Limon" }));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ayuda.png"))); // NOI18N
        jLabel3.setToolTipText("Enter the email of the user you want to edit");

        jLabel5.setText("id");

        jTextFieldIdClient.setEditable(false);

        jLabel20.setText("LastName1:");

        jLabel21.setText("LastName2:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(57, 57, 57)
                                .addComponent(jTextFieldIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabelNombreCliente)
                                        .addGap(31, 31, 31)
                                        .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabelCorreoCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabelTelefonoCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldPhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldLastNameClient)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jTextFieldLastName2Client, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelAdress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                                .addComponent(jTextFieldAdressClient, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEditarCliente)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAgregarCliente)
                                .addGap(26, 26, 26)
                                .addComponent(jButtonEliminarCliente)))
                        .addContainerGap(318, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelProvince)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxProvinceClient, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreCliente)
                    .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldLastNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldLastName2Client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCorreoCliente)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefonoCliente)
                    .addComponent(jTextFieldPhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelProvince)
                    .addComponent(jComboBoxProvinceClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminarCliente)
                    .addComponent(jButtonAgregarCliente)
                    .addComponent(jButtonEditarCliente)
                    .addComponent(jTextFieldAdressClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAdress))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Clientes", jPanel3);

        jLabel7.setText("Email:");

        jLabel8.setText("Name:");

        jLabel9.setText("Code:");

        jLabel10.setText("User:");

        jTextFieldCorreoAgente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCorreoAgenteFocusGained(evt);
            }
        });
        jTextFieldCorreoAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoAgenteActionPerformed(evt);
            }
        });

        jButtonAgregarAgente.setText("add agent");
        jButtonAgregarAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarAgenteActionPerformed(evt);
            }
        });

        jButtonEditAgent.setText("edit agent");
        jButtonEditAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditAgentActionPerformed(evt);
            }
        });

        jButtonDeleteAgent.setText("delete agent");
        jButtonDeleteAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteAgentActionPerformed(evt);
            }
        });

        jLabel11.setText("password:");

        jButtonCleanAgent.setText("clean");
        jButtonCleanAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanAgentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButtonAgregarAgente)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditAgent)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteAgent))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordFieldAgente))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(36, 36, 36)
                                .addComponent(jTexFieldUsuarioAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(34, 34, 34)
                                .addComponent(jTextFieldCodigoAgente))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNombreAgente)
                                    .addComponent(jTextFieldCorreoAgente))))
                        .addGap(28, 28, 28)
                        .addComponent(jButtonCleanAgent)))
                .addContainerGap(857, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldCorreoAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCleanAgent))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldNombreAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldCodigoAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTexFieldUsuarioAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jPasswordFieldAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarAgente)
                    .addComponent(jButtonEditAgent)
                    .addComponent(jButtonDeleteAgent))
                .addGap(58, 58, 58))
        );

        jTabbedPane1.addTab("Agentes", jPanel4);

        jLabel6.setText("ID");

        jLabel12.setText("NAME");

        jLabel13.setText("LAST NAME 1");

        jLabel14.setText("LAST NAME 2");

        jLabel15.setText("PHONE");

        jLabel16.setText("TYPE VEHICLE");

        jLabel17.setText("PLATE");

        jLabel18.setText("CEDULA");

        jLabel19.setText("AGE");

        jTextFieldNameDriver.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNameDriverFocusGained(evt);
            }
        });

        jTextFieldLastName2Driver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLastName2DriverActionPerformed(evt);
            }
        });

        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("EDIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextFieldCedulaDriver.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCedulaDriverFocusGained(evt);
            }
        });
        jTextFieldCedulaDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCedulaDriverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIDDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNameDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLastName1Driver, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPhoneDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(25, 25, 25)
                                .addComponent(jTextFieldTypeVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                    .addComponent(jTextFieldAgeDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel18))
                                    .addGap(25, 25, 25)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldPlateDriver, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                        .addComponent(jTextFieldCedulaDriver))))))
                    .addComponent(jTextFieldLastName2Driver, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jButton2)
                .addGap(59, 59, 59)
                .addComponent(jButton3)
                .addGap(67, 67, 67)
                .addComponent(jButton1))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldIDDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldPlateDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldNameDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTextFieldCedulaDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldLastName1Driver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldLastName2Driver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextFieldPhoneDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTextFieldAgeDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextFieldTypeVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Conductores", jPanel6);

        IdRestaurant.setText("ID:");

        NameRestaurant.setText("Name:");

        jLabel2.setText("Location:");

        jLabel22.setText("Price:");

        jLabel23.setText("Restaurant:");

        jLabel24.setText("Type:");

        jComboBoxRestaurant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "McDonalds", "Burger King", "Carls Jr.", "Domino's Pizza", "KFC", "Pizza Hut", "Taco Bell" }));

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jButtonAddProduct.setText("ADD");
        jButtonAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProductActionPerformed(evt);
            }
        });

        jButtonUpdateProduct.setText("UPDATE");

        jButtonDeleteProduct.setText("DELETE");

        jButtonDireccionProducto.setText("Buscar");
        jButtonDireccionProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDireccionProductoActionPerformed(evt);
            }
        });

        jTextFieldAdressProduct.setEditable(false);

        jButtonCleanProduct.setText("CLEAN");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ayuda.png"))); // NOI18N
        jLabel25.setToolTipText("Selected:\n1-food  \n2-drink  \n3-dessert  \n4-other  ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(NameRestaurant)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldNameProduct))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(IdRestaurant)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTexFieldIdProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldAdressProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAddProduct)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldPriceProduct)
                                .addComponent(jComboBoxRestaurant, 0, 1, Short.MAX_VALUE)
                                .addComponent(jComboBoxType, 0, 112, Short.MAX_VALUE)))))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButtonUpdateProduct)
                        .addGap(79, 79, 79)
                        .addComponent(jButtonDeleteProduct)
                        .addGap(67, 67, 67)
                        .addComponent(jButtonCleanProduct))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDireccionProducto))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(577, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdRestaurant)
                    .addComponent(jTexFieldIdProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameRestaurant))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonDireccionProducto)
                    .addComponent(jTextFieldAdressProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(13, 13, 13)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jComboBoxRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel25))
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddProduct)
                    .addComponent(jButtonUpdateProduct)
                    .addComponent(jButtonDeleteProduct)
                    .addComponent(jButtonCleanProduct))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Producto", jPanel7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1190, 410));

        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agent Information");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Name:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jLabelCodigo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigo.setText("Code:");
        getContentPane().add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jLabelBorder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelBorder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabelBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 530, 130));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoMediano.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelFonoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoAzul.png"))); // NOI18N
        getContentPane().add(jLabelFonoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        // TODO add your handling code here:
        int salida = JOptionPane.showConfirmDialog(null,
                "Realmente desea salir de la apilcación?", "Confirmar salida",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (salida == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_SalirMouseClicked

    private void jTextFieldPhoneClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneClientActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreClienteActionPerformed

    /**
     *
     * LLena el AutoCompleter con los correos.
     */
    private void fillAutoCompleterClients() {
        textAutoCompleterClient.removeAllItems();
        for (int i = 0; i < clientsList.size(); i++) {
            System.out.println(clientsList.get(i).toString());
            textAutoCompleterClient.addItem(clientsList.get(i).getEmail());
        }
    }

    private void fillAutoCompleterAgents() {
        textAutoCompleterAgent.removeAllItems();
        for (int i = 0; i < agentsList.size(); i++) {
            System.out.println(agentsList.get(i).toString());
            textAutoCompleterAgent.addItem(agentsList.get(i).getEmail());
        }
    }

    private void fillAutoCompleterDrivers() {
        textAutoCompleterDriver.removeAllItems();
        for (int i = 0; i < driversList.size(); i++) {
            textAutoCompleterDriver.addItem(driversList.peek().getName());
            driversList.add(driversList.poll());
        }
    }

    /**
     * Metodo para exportar a pdf
     *
     * @param evt
     */
    private void jButtonPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPDFActionPerformed

        try {
            jTableOrders.print(JTable.PrintMode.FIT_WIDTH);

        } catch (java.awt.print.PrinterException e) {
            System.err.format("error de impresion", e.getMessage());
        }
    }//GEN-LAST:event_jButtonPDFActionPerformed

    private void jButtonExcellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcellActionPerformed
        // TODO add your handling code here:

        Excel crearExcel = new Excel();
        crearExcel.crear_Excel(jTableOrders, "Control General");

    }//GEN-LAST:event_jButtonExcellActionPerformed

    private void jButtonAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarClienteActionPerformed
        // TODO add your handling code here:

        //Verifica y añade un cliente en caso de que éste no esté en la lista
        Client c = new Client(jTextFieldIdClient.getText(), jTextFieldNombreCliente.getText(),
                jTextFieldLastNameClient.getText(), jTextFieldLastName2Client.getText(), jTextFieldEmail.getText(), jTextFieldPhoneClient.getText(),
                jComboBoxProvinceClient.getSelectedItem().toString(), jTextFieldAdressClient.getText());
        logic.saveClients(c);

        jTextFieldAdressClient.setText("");
        jTextFieldIdClient.setText("");
        jTextFieldLastNameClient.setText("");
        jTextFieldLastName2Client.setText("");
        jTextFieldIdClient.setText("");
        jTextFieldEmail.setText("");
        jTextFieldNombreCliente.setText("");
        jTextFieldPhoneClient.setText("");


    }//GEN-LAST:event_jButtonAgregarClienteActionPerformed

    private void jTextFieldCorreoAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoAgenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoAgenteActionPerformed

    private void jTextFieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusGained
        // TODO add your handling code here:
        for (int i = 0; i < clientsList.size(); i++) {
            if (jTextFieldEmail.getText().equals(clientsList.get(i).getEmail())) {
                jTextFieldIdClient.setText(clientsList.get(i).getId());
                jTextFieldNombreCliente.setText(clientsList.get(i).getName());
                jTextFieldLastNameClient.setText(clientsList.get(i).getLastName1());
                jTextFieldLastName2Client.setText(clientsList.get(i).getLastName2());
                jComboBoxProvinceClient.setSelectedItem(clientsList.get(i).getProvince());
                jTextFieldPhoneClient.setText(clientsList.get(i).getPhone());
                jTextFieldAdressClient.setText(clientsList.get(i).getAdress());
            }
        }
    }//GEN-LAST:event_jTextFieldEmailFocusGained

    private void jButtonEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarClienteActionPerformed
        // TODO add your handling co de here:
        Client c = new Client(jTextFieldIdClient.getText(), jTextFieldNombreCliente.getText(),
                jTextFieldLastName2Client.getText(), jTextFieldLastName2Client.getText(), jTextFieldEmail.getText(), jTextFieldPhoneClient.getText(),
                jComboBoxProvinceClient.getSelectedItem().toString(), jTextFieldAdressClient.getText());
        logic.deleteClient(c);
    }//GEN-LAST:event_jButtonEliminarClienteActionPerformed

    private void jButtonEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarClienteActionPerformed
        // TODO add your handling code here:
        Client c = new Client(jTextFieldIdClient.getText(), jTextFieldNombreCliente.getText(),
                jTextFieldLastNameClient.getText(), jTextFieldLastName2Client.getText(), jTextFieldEmail.getText(), jTextFieldPhoneClient.getText(),
                jComboBoxProvinceClient.getSelectedItem().toString(), jTextFieldAdressClient.getText());
        logic.updateClient(c);


    }//GEN-LAST:event_jButtonEditarClienteActionPerformed

    private void jButtonAgregarAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarAgenteActionPerformed
        // TODO add your handling code here:
        Agent a = new Agent(jTextFieldNombreAgente.getText(), jTextFieldCorreoAgente.getText(),
                jTexFieldUsuarioAgente.getText(), jPasswordFieldAgente.getText(), jTextFieldCodigoAgente.getText());
        logic.saveAgent(a);

        jTexFieldUsuarioAgente.setText("");
        jTextFieldCodigoAgente.setText("");
        jTextFieldCorreoAgente.setText("");
        jPasswordFieldAgente.setText("");
        jTextFieldNombreAgente.setText("");

    }//GEN-LAST:event_jButtonAgregarAgenteActionPerformed

    private void jTextFieldCorreoAgenteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCorreoAgenteFocusGained
        // TODO add your handling code here:
        for (int i = 0; i < agentsList.size(); i++) {
            if (jTextFieldCorreoAgente.getText().equals(agentsList.get(i).getEmail())) {
                jTextFieldNombreAgente.setText(agentsList.get(i).getName());
                jTexFieldUsuarioAgente.setText(agentsList.get(i).getUser());
                jTextFieldCodigoAgente.setText(agentsList.get(i).getCode());
                jPasswordFieldAgente.setText(agentsList.get(i).getPassword());
            }
        }

    }//GEN-LAST:event_jTextFieldCorreoAgenteFocusGained

    private void jButtonCleanAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanAgentActionPerformed
        // TODO add your handling code here:
        jTexFieldUsuarioAgente.setText("");
        jTextFieldCodigoAgente.setText("");
        jTextFieldCorreoAgente.setText("");
        jPasswordFieldAgente.setText("");
        jTextFieldNombreAgente.setText("");
    }//GEN-LAST:event_jButtonCleanAgentActionPerformed

    private void jButtonEditAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditAgentActionPerformed
        // TODO add your handling code here:
        Agent agent = new Agent(jTextFieldNombreAgente.getText(), jTextFieldCorreoAgente.getText(),
                jTexFieldUsuarioAgente.getText(), jPasswordFieldAgente.getText(),
                jTextFieldCodigoAgente.getText());
        logic.updateAgent(agent);

        jTexFieldUsuarioAgente.setText("");
        jTextFieldCodigoAgente.setText("");
        jTextFieldCorreoAgente.setText("");
        jPasswordFieldAgente.setText("");
        jTextFieldNombreAgente.setText("");

    }//GEN-LAST:event_jButtonEditAgentActionPerformed

    private void jButtonDeleteAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteAgentActionPerformed
        // TODO add your handling code here:
        Agent agent = new Agent(jTextFieldNombreAgente.getText(), jTextFieldCorreoAgente.getText(),
                jTexFieldUsuarioAgente.getText(), jPasswordFieldAgente.getText(),
                jTextFieldCodigoAgente.getText());
        logic.deleteAgent(agent);
        jTexFieldUsuarioAgente.setText("");
        jTextFieldCodigoAgente.setText("");
        jTextFieldCorreoAgente.setText("");
        jPasswordFieldAgente.setText("");
        jTextFieldNombreAgente.setText("");

    }//GEN-LAST:event_jButtonDeleteAgentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Driver d = new Driver(jTextFieldIDDriver.getText(), jTextFieldNameDriver.getText(),
                jTextFieldLastName1Driver.getText(), jTextFieldLastName2Driver.getText(),
                jTextFieldAgeDriver.getText(), jTextFieldTypeVehicle.getText(),
                jTextFieldPhoneDriver.getText(), jTextFieldPlateDriver.getText(),
                jTextFieldCedulaDriver.getText());
        logic.deleteDriver(d);

        jTextFieldIDDriver.setText("");
        jTextFieldAgeDriver.setText("");
        jTextFieldNameDriver.setText("");
        jTextFieldLastName1Driver.setText("");
        jTextFieldLastName2Driver.setText("");
        jTextFieldPhoneDriver.setText("");
        jTextFieldPlateDriver.setText("");
        jTextFieldTypeVehicle.setText("");
        jTextFieldCedulaDriver.setText("");


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Driver driver = new Driver(jTextFieldIDDriver.getText(),
                jTextFieldNameDriver.getText(), jTextFieldLastName1Driver.getText(),
                jTextFieldLastName2Driver.getText(), jTextFieldAgeDriver.getText(),
                jTextFieldTypeVehicle.getText(), jTextFieldPhoneDriver.getText(),
                jTextFieldPlateDriver.getText(), jTextFieldCedulaDriver.getText());
        logic.saveDrivers(driver);

        jTextFieldIDDriver.setText("");
        jTextFieldAgeDriver.setText("");
        jTextFieldNameDriver.setText("");
        jTextFieldLastName1Driver.setText("");
        jTextFieldLastName2Driver.setText("");
        jTextFieldPhoneDriver.setText("");
        jTextFieldPlateDriver.setText("");
        jTextFieldTypeVehicle.setText("");
        jTextFieldCedulaDriver.setText("");


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldClientFiltrerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldClientFiltrerKeyTyped
        // TODO add your handling code here:

        jTextFieldClientFiltrer.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)" + jTextFieldClientFiltrer.getText(), 0));
                //El "(?i)" es para que funcione con mayusculas y minusculas
            }

        });

        trs = new TableRowSorter(tableModel);
        jTableOrders.setRowSorter(trs);
    }//GEN-LAST:event_jTextFieldClientFiltrerKeyTyped

    private void jTextFieldOrderFiltrerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldOrderFiltrerKeyTyped
        // TODO add your handling code here:

        jTextFieldOrderFiltrer.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_BACK_SPACE && jTextFieldOrderFiltrer.getText().equals("")) {
                    jTextFieldClientFiltrer.setText("");
                } else {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)" + jTextFieldOrderFiltrer.getText(), 1));
                    //El "(?i)" es para que funcione con mayusculas y minusculas
                }
            }

        });

        trs = new TableRowSorter(tableModel);
        jTableOrders.setRowSorter(trs);

    }//GEN-LAST:event_jTextFieldOrderFiltrerKeyTyped

    private void jTextFieldLastName2DriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLastName2DriverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLastName2DriverActionPerformed

    private void jTextFieldCedulaDriverFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCedulaDriverFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldCedulaDriverFocusGained

    private void jTextFieldCedulaDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaDriverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaDriverActionPerformed

    private void jTextFieldNameDriverFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNameDriverFocusGained
        // TODO add your handling code here:
        for (int i = 0; i < driversList.size(); i++) {
            if (driversList.peek().getName().equals(jTextFieldNameDriver.getText())) {
                jTextFieldIDDriver.setText(String.valueOf(driversList.peek().getId()));
                jTextFieldLastName1Driver.setText(driversList.peek().getLastName1());
                jTextFieldLastName2Driver.setText(driversList.peek().getLastName2());
                jTextFieldPhoneDriver.setText(driversList.peek().getPhone());
                jTextFieldPlateDriver.setText(driversList.peek().getPlate());
                jTextFieldAgeDriver.setText(driversList.peek().getAge());
                jTextFieldCedulaDriver.setText(driversList.peek().getCedula());
                jTextFieldTypeVehicle.setText(driversList.peek().getType());

            }
            driversList.add(driversList.poll());
        }
    }//GEN-LAST:event_jTextFieldNameDriverFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Driver d = new Driver(jTextFieldIDDriver.getText(), jTextFieldNameDriver.getText(),
                jTextFieldLastName1Driver.getText(), jTextFieldLastName2Driver.getText(),
                jTextFieldAgeDriver.getText(), jTextFieldTypeVehicle.getText(),
                jTextFieldPhoneDriver.getText(), jTextFieldPlateDriver.getText(),
                jTextFieldCedulaDriver.getText());
        logic.updateDriversFile(d);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            new Thread(new Logic()).start();

        } catch (ListException | IOException ex) {
            Logger.getLogger(AgentInterface.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButtonDireccionProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDireccionProductoActionPerformed
        // TODO add your handling code here:
        /**
         * llamamos el metodo que permite cargar la ventana
         */
        JFileChooser file = new JFileChooser();
        file.showOpenDialog(this);
        /**
         * abrimos el archivo seleccionado
         */
        File abre = file.getSelectedFile();
        jTextFieldAdressProduct.setText(abre.toString());
        
    }//GEN-LAST:event_jButtonDireccionProductoActionPerformed

    private void jButtonAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProductActionPerformed
        try {
            // TODO add your handling code here:
            Product p;
            p = new Product(jTextFieldNameProduct.getText(),
                    Double.parseDouble(jTextFieldPriceProduct.getText()), jTextFieldAdressProduct.getText(),
                    jComboBoxRestaurant.getSelectedItem().toString(),
                    jComboBoxType.getSelectedIndex()+1);
            
            logic.saveProducts(p);
            jTextFieldNameProduct.setText("");
            jTextFieldPriceProduct.setText("");        
            jTextFieldAdressProduct.setText("");
            
        } catch (IOException ex) {
            Logger.getLogger(AdministratorInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonAddProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdministratorInterface().setVisible(true);
                } catch (ListException | IOException | StackException ex) {
                    Logger.getLogger(AdministratorInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdRestaurant;
    private javax.swing.JLabel NameRestaurant;
    private javax.swing.JButton Salir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAddProduct;
    private javax.swing.JButton jButtonAgregarAgente;
    private javax.swing.JButton jButtonAgregarCliente;
    private javax.swing.JButton jButtonCleanAgent;
    private javax.swing.JButton jButtonCleanProduct;
    private javax.swing.JButton jButtonDeleteAgent;
    private javax.swing.JButton jButtonDeleteProduct;
    private javax.swing.JButton jButtonDireccionProducto;
    private javax.swing.JButton jButtonEditAgent;
    private javax.swing.JButton jButtonEditarCliente;
    private javax.swing.JButton jButtonEliminarCliente;
    private javax.swing.JButton jButtonExcell;
    private javax.swing.JButton jButtonPDF;
    private javax.swing.JButton jButtonUpdateProduct;
    private javax.swing.JComboBox<String> jComboBoxProvinceClient;
    private javax.swing.JComboBox<String> jComboBoxRestaurant;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAdress;
    private javax.swing.JLabel jLabelBorder;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCorreoCliente;
    private javax.swing.JLabel jLabelFonoPrincipal;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreCliente;
    private javax.swing.JLabel jLabelProvince;
    private javax.swing.JLabel jLabelTelefonoCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordFieldAgente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableOrders;
    private javax.swing.JTextField jTexFieldIdProduct;
    private javax.swing.JTextField jTexFieldUsuarioAgente;
    private javax.swing.JTextField jTextFieldAdressClient;
    private javax.swing.JTextField jTextFieldAdressProduct;
    private javax.swing.JTextField jTextFieldAgeDriver;
    private javax.swing.JTextField jTextFieldCedulaDriver;
    private javax.swing.JTextField jTextFieldClientFiltrer;
    private javax.swing.JTextField jTextFieldCodigoAgente;
    private javax.swing.JTextField jTextFieldCorreoAgente;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIDDriver;
    private javax.swing.JTextField jTextFieldIdClient;
    private javax.swing.JTextField jTextFieldLastName1Driver;
    private javax.swing.JTextField jTextFieldLastName2Client;
    private javax.swing.JTextField jTextFieldLastName2Driver;
    private javax.swing.JTextField jTextFieldLastNameClient;
    private javax.swing.JTextField jTextFieldNameDriver;
    private javax.swing.JTextField jTextFieldNameProduct;
    private javax.swing.JTextField jTextFieldNombreAgente;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JTextField jTextFieldOrderFiltrer;
    private javax.swing.JTextField jTextFieldPhoneClient;
    private javax.swing.JTextField jTextFieldPhoneDriver;
    private javax.swing.JTextField jTextFieldPlateDriver;
    private javax.swing.JTextField jTextFieldPriceProduct;
    private javax.swing.JTextField jTextFieldTypeVehicle;
    // End of variables declaration//GEN-END:variables
}
